### ISSUE TITLE
Widget does not work in Mendix 9.7

### ISSUE THREAD

**Issue by ChrisdeG** [mendixlabs/mendix-dynamic-table#15]
Hi Jelte,

In Mendix 9.7 i get the message in the test project 

window.mx.meta.getEntity(...).isPersistable is not a function 

Widget is not working. In the ui I get the message

An error occurred in a "com.mendix.widget.custom.dynamictable.DynamicTable" widget. Check updates for the widget in the Mendix App Store or contact the widget developer.

(It seems to me that this message should mention 'Matrix' as well).

Regards,
Chris

**Comment by ChrisdeG** [comment]
I downloaded the testproject, but there was already a fix.
